name: "Display secret"

on:
  push:

env:
  SUPER_SECRET: ${{ secret.SUPER_SECRET }}

jobs:
  confidential_data:
    name: "Display secret"
    runs-on: ubuntu-latest
    steps:
      - name: "Display secret"
        run: echo "La valeur de SUPER_SECRET est ${{env.SUPER_SECRET}}"