name: "Display secret"

on:
  push:

jobs:
  confidential_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display secret
        run: echo "La valeur de SUPER_SECRET est '${{ secrets.SUPER_SECRET }}'"