name: Confidential Data

on:
  push:
  pull_request:

jobs:
  confidential_data:
    runs-on: ubuntu-latest

    steps:
      - name: Show secret value
        run: |
          echo "La valeur de SUPER_SECRET est : ${{ secrets.SUPER_SECRET }}"
