name: Display Readme

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: Display readme.md
        run: cat Readme.md
