name:  build_and_publish

on:
  push:

jobs:
   build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3

      - name: login to docker hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-activation@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/exo-4-4:demo




