name: Execute script demo

on:
  push:

jobs:
   execute_script:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - run: python demo.py
