name: information display

on:
  push:

jobs:
  information_display:
    runs-on: ubuntu-latest

    steps:
    - name: Affichage d'une notice
      run: echo "Ceci est une notice."

    - name: Affichage d'un avertissement
      run: echo "Ceci est un avertissement."
      continue-on-error: true

    - name: Affichage d'une erreur
      run: echo "Une erreur est survenue." && exit 1
